version: '3'

services:
  db:
    restart: always
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql
  anonengine:
    build: ./application
    container_name: anonengine
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "5003:5003"
    env_file:
      - .env
    volumes:
      - .:/opt/services/anonengine/src
  dash:
    build: ./dash
    container_name: dash
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "5004:5004"
    env_file:
      - .env
    volumes:
      - .:/opt/services/dash/src
  web:
    build: ./nginx
    container_name: web
    restart: always
    depends_on:
      - anonengine
    links:
      - anonengine
    ports:
      - "8880:8880"
      - "8881:8881"
volumes:
  postgres: