FROM postgres:latest

LABEL maintainer="Sisay Chala <chala@fit.fraunhofer.de>" 

ENV POSTGRES_USER="postgres"
ENV POSTGRES_PASSWORD="password"
ENV POSTGRES_DB="pubdb"
ENV POSTGRES_PORT="5442"
ENV POSTGRES_HOST="db"
ENV APP_SECRET_KEY="your_secrete_key"

EXPOSE 5442

VOLUME /var/lib/postgresql



